/// Plugin system for special files and dynamic content
///
/// This module implements plugins for:
/// - func: Dynamic files generated by callbacks (.version, .members, etc.)
/// - link: Symbolic links
///
/// Each plugin is implemented in its own source file:
/// - version.rs: .version plugin - cluster version information
/// - members.rs: .members plugin - cluster member list
/// - vmlist.rs: .vmlist plugin - VM/CT list
/// - rrd.rs: .rrd plugin - system metrics
/// - clusterlog.rs: .clusterlog plugin - cluster log entries
/// - debug.rs: .debug plugin - debug level control
mod clusterlog;
mod debug;
mod members;
mod registry;
mod rrd;
mod types;
mod version;
mod vmlist;

// Re-export core types (only Plugin trait is used outside this module)
pub use types::Plugin;

// Re-export registry
pub use registry::{PluginRegistry, init_plugins};

#[cfg(test)]
pub use registry::init_plugins_for_test;
